<script setup lang="ts">
import { useServerStore } from '@/stores/server';
import { useAuthStore } from '@/stores/auth';
import ScreenSetupArt from '@/components/ScreenSetupArt.vue';
const server = useServerStore(); const auth = useAuthStore();
</script>
<template>
<header class="pitlane-heading"><div><span class="pitlane-eyebrow">A place for everything</span><h1>Garage<span class="text-accent">.</span></h1><p>Your equipment, your collection, and the people who make it a club.</p></div><RouterLink to="/garage/advanced" class="pitlane-button">Advanced tools →</RouterLink></header>
<div class="pitlane-grid garage-workspaces">
  <RouterLink to="/garage/rigs" class="pitlane-card"><div class="garage-art"><ScreenSetupArt setup="triple" /></div><h2>Rigs & cameras</h2><p>Seats, screens and streams. Keep the equipment ready for whoever drives next.</p><span>Open the rigs →</span></RouterLink>
  <RouterLink v-if="auth.isAdmin" to="/garage/content" class="pitlane-card"><div class="garage-art collection-art"><span>Cars<br />& tracks.</span></div><h2>Your driving collection</h2><p>Installed cars, liveries, tracks, layouts and weather. Find the next combination.</p><span>Browse the library →</span></RouterLink>
  <RouterLink to="/garage/advanced" class="pitlane-card"><div class="garage-art tools-art"><span>Fine<br />tuning.</span></div><h2>Advanced</h2><p>Every control, with its scope and consequences. Search when you need something specific.</p><span>Find a tool →</span></RouterLink>
</div>
<section class="pitlane-card pitlane-section garage-servers"><span class="pitlane-eyebrow">The places you drive</span><h2>Your servers</h2><div class="garage-server-row" v-for="instance in server.instanceList" :key="instance.id"><div><h3>{{ instance.name }}</h3><p>{{ server.statusErrors[instance.id] ? 'Status unavailable' : instance.running ? `${instance.players} drivers on track` : 'Stopped' }}</p></div><div class="pitlane-actions"><RouterLink :to="`/server/${instance.id}`" class="pitlane-button">Open server</RouterLink><RouterLink :to="`/queue?instance=${instance.id}`" class="pitlane-button">Running order</RouterLink></div></div><p v-if="!server.instanceList.length">{{ server.loaded ? 'No servers configured yet.' : 'Loading servers…' }}</p><RouterLink v-if="auth.isAdmin" to="/settings/instances" class="pitlane-button">Manage servers & ports →</RouterLink></section>
<section class="pitlane-card pitlane-section garage-club"><span class="pitlane-eyebrow">The people and the memories</span><h2>The club</h2><p>One home for drivers, records, access and saved moments.</p><div class="pitlane-actions mt-5"><RouterLink to="/drivers" class="pitlane-button">Drivers</RouterLink><RouterLink to="/leaderboard" class="pitlane-button">Club records</RouterLink><RouterLink to="/broadcast" class="pitlane-button">Spectator display</RouterLink><RouterLink v-if="auth.canOperate" to="/guest-drivers" class="pitlane-button">Guest roster</RouterLink><RouterLink v-if="auth.isAdmin" to="/settings/users" class="pitlane-button">Accounts & roles</RouterLink><RouterLink v-if="auth.isAdmin" to="/maintenance" class="pitlane-button">Backups & restore</RouterLink></div></section>
</template>
<style scoped>
.garage-workspaces>a{display:block;padding:0 0 24px;overflow:hidden}.garage-workspaces h2,.garage-workspaces p,.garage-workspaces>a>span{margin:20px 24px 0;display:block}.garage-art{height:195px;background:var(--color-surface-2);display:grid;place-items:center}.garage-art img{width:90%;height:185px;object-fit:contain}.garage-art span{font-size:40px;line-height:1;letter-spacing:-.06em}.collection-art{background:var(--color-art-sand)}.tools-art{background:var(--color-art-mist)}.garage-servers{border-top:3px solid var(--color-ok)}.garage-club{border-top:3px solid var(--color-accent)}.garage-server-row{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid var(--color-line);padding:22px 0}.garage-server-row p{margin-top:4px}
</style>
