<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {api} from '@/lib/api';
import {useConfirmStore} from '@/stores/confirm';
import type {ContentMetadata} from '@/stores/content';
const confirm=useConfirmStore();
interface Change{id:number;kind:string;key:string;layout:string;before:ContentMetadata;after:ContentMetadata;created_at:number;undone_at:number|null}
interface Cleanup{targets:{name:string;bytes:number;modified_at:number}[];token:string;checked_at:number;exclusions:string[]}
const changes=ref<Change[]>([]),preview=ref<Cleanup|null>(null),busy=ref(false),error=ref(''),message=ref('');
async function load(){try{changes.value=(await api.get<{items:Change[]}>('/api/recovery/changes')).items}catch(e){error.value=String(e)}}
async function undo(change:Change){if(!await confirm.ask({title:`Undo changes to ${change.key}?`,message:'Restore the metadata values shown below. Later edits block this operation.',confirmLabel:'Undo this change'}))return;busy.value=true;try{await api.post(`/api/recovery/changes/${change.id}/undo`);message.value='Metadata restored.';await load()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function inspect(){busy.value=true;error.value='';try{preview.value=await api.get<Cleanup>('/api/recovery/cleanup')}catch(e){error.value=String(e)}finally{busy.value=false}}
async function clean(){if(!preview.value||!await confirm.ask({title:'Remove these abandoned upload archives?',message:`Permanently remove the ${preview.value.targets.length} files in this preview.`,confirmLabel:'Remove listed files',tone:'danger'}))return;busy.value=true;try{const r=await api.post<{removed:string[]}>('/api/recovery/cleanup',{token:preview.value.token});message.value=`Removed ${r.removed.length} upload archives.`;preview.value=null}catch(e){error.value=String(e)}finally{busy.value=false}}
onMounted(load);
</script>
<template><header class="pitlane-heading"><div><span class="pitlane-eyebrow">Garage / Recovery</span><h1>A clear way back.</h1><p>Review supported changes and clean up identified abandoned uploads.</p></div><RouterLink to="/maintenance" class="pitlane-button">Backups & staged restore</RouterLink></header><div v-if="error" class="pitlane-error" role="alert">{{ error }}</div><p v-if="message" role="status" class="mb-5">{{ message }}</p><section class="pitlane-card"><h2>Abandoned upload archives</h2><p>Only regular upload files older than 24 hours in ServerManager’s temporary folder are eligible. Active imports block cleanup.</p><button class="pitlane-button mt-4" :disabled="busy" @click="inspect">Preview cleanup</button><div v-if="preview" class="mt-5"><p>Checked {{ new Date(preview.checked_at).toLocaleString() }}</p><p v-if="!preview.targets.length">No eligible abandoned uploads.</p><ul><li v-for="target in preview.targets" :key="target.name">{{ target.name }} · {{ target.bytes.toLocaleString() }} bytes</li></ul><details class="mt-4"><summary>Excluded from cleanup</summary><ul><li v-for="exclusion in preview.exclusions" :key="exclusion">{{ exclusion }}</li></ul></details><button v-if="preview.targets.length" class="pitlane-button mt-5" :disabled="busy" @click="clean">Remove these files</button></div></section><section class="pitlane-section"><h2 class="text-2xl mb-3">Recent library changes</h2><p class="text-muted mb-6">Undo supports local content names, tags, notes and archive state. Server operations, imports, file deletion and restore have their own recovery paths.</p><p v-if="!changes.length">No supported metadata changes have been recorded yet.</p><article v-for="change in changes" :key="change.id" class="pitlane-card mb-4"><div class="flex justify-between gap-5"><h3>{{ change.key }} {{ change.layout }} · {{ change.kind }}</h3><small>{{ new Date(change.created_at).toLocaleString() }}</small></div><div class="pitlane-grid mt-4"><div><b>Before</b><p>{{ change.before.display_name||'Original name' }} · {{ change.before.archived?'Archived':'Available' }}</p><p>{{ change.before.tags.join(', ') }}</p><p>{{ change.before.notes }}</p></div><div><b>After</b><p>{{ change.after.display_name||'Original name' }} · {{ change.after.archived?'Archived':'Available' }}</p><p>{{ change.after.tags.join(', ') }}</p><p>{{ change.after.notes }}</p></div></div><div class="pitlane-actions mt-5"><button class="pitlane-button" :disabled="busy||!!change.undone_at" @click="undo(change)">{{ change.undone_at?'Undone':'Undo this change' }}</button><RouterLink :to="`/garage/content/${change.kind}/${encodeURIComponent(change.key)}?layout=${encodeURIComponent(change.layout)}`" class="pitlane-button">Current details</RouterLink></div></article></section></template>
