<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue';
import { useRoute,useRouter } from 'vue-router';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth';
import { useServerStore } from '@/stores/server';
import { screenSetups,type ScreenSetup } from '@/lib/screenSetups';
import { useDriverStreams,type CameraSource } from '@/lib/useDriverStreams';
import Sheet from '@/components/ui/Sheet.vue';
import ScreenSetupArt from '@/components/ScreenSetupArt.vue';
import {useUnsavedGuard} from '@/lib/useUnsavedGuard';
import {listGuestDrivers,assignLiveDriver,type GuestDriver} from '@/lib/guestDriversApi';
import {listDrivers} from '@/lib/driversApi';
import type {DriverSummary} from '@/types/driverStats';
import { useConfirmStore } from '@/stores/confirm';
interface Gear {id:string;type:string;name:string;notes:string}
interface Rig {id:number;revision:number;name:string;location:string;display:ScreenSetup;notes:string;usual_driver_guid:string;usual_guest_id:number|null;gear:Gear[]}
const newGearId=()=>crypto.randomUUID();
const route=useRoute(),router=useRouter(),auth=useAuthStore(),server=useServerStore(),confirm=useConfirmStore(),streams=useDriverStreams();
const rigs=ref<Rig[]>([]),loaded=ref(false),error=ref(''),saving=ref(false),draft=ref<Rig|null>(null),camera=ref<CameraSource|null>(null),check=ref('');
const search=ref(''),draftBaseline=ref(''),cameraBaseline=ref('');
const guests=ref<GuestDriver[]>([]),accounts=ref<DriverSummary[]>([]),handover=ref<{instanceId:number;carId:number;name:string}|null>(null),nextGuest=ref<number|null>(null);
const closeEditor=useUnsavedGuard(()=>!!draft.value&&JSON.stringify(draft.value)!==draftBaseline.value||!!camera.value&&JSON.stringify(camera.value)!==cameraBaseline.value);
function currentSeats(rig:Rig){const guids=attached(rig.id).map(s=>s.driver_guid).filter(Boolean);return server.instanceList.flatMap(i=>i.drivers.filter(d=>d.connected&&guids.includes(d.guid)).map(d=>({instanceId:i.id,carId:d.car_id,name:d.name}))) }
async function changeDriver(){if(!handover.value)return;saving.value=true;error.value='';try{await assignLiveDriver(handover.value.instanceId,handover.value.carId,nextGuest.value);handover.value=null;await server.bootstrapLiveState()}catch(e){error.value=String(e)}finally{saving.value=false}}
const usualName=(rig:Rig)=>rig.usual_guest_id?guests.value.find(g=>g.id===rig.usual_guest_id)?.name??`Guest ${rig.usual_guest_id}`:accounts.value.find(d=>d.guid===rig.usual_driver_guid)?.name??'Anyone in the club';
const selected=computed(()=>rigs.value.find(r=>r.id===Number(route.params.rigId)));
const visible=computed(()=>rigs.value.filter(r=>[r.name,r.location,r.notes,...r.gear.map(g=>g.name)].join(' ').toLowerCase().includes(search.value.toLowerCase())));
const artwork=(display:string)=>screenSetups.find(s=>s.id===display) ?? screenSetups[0];
const attached=(id:number)=>streams.sources.value.filter(s=>s.rig_id===id);
function occupants(rig:Rig){const guids=attached(rig.id).map(s=>s.driver_guid).filter(Boolean);return server.instanceList.flatMap(i=>i.drivers.filter(d=>d.connected&&guids.includes(d.guid)).map(d=>`${d.name} · ${i.name}`))}
async function load(){error.value='';try{rigs.value=(await api.get<{rigs:Rig[]}>('/api/rigs')).rigs;await streams.loadStreams();[guests.value,accounts.value]=await Promise.all([listGuestDrivers(),listDrivers().then(items=>items.filter(d=>!!d.guid))]);loaded.value=true;const source=streams.sources.value.find(s=>s.id===route.query.source);if(source&&auth.isAdmin)editCamera(source)}catch(e){error.value=String(e)}}
function edit(rig?:Rig){error.value='';draft.value=rig?JSON.parse(JSON.stringify(rig)):{id:0,revision:0,name:'',location:'',display:'triple',notes:'',usual_driver_guid:'',usual_guest_id:null,gear:[]};draftBaseline.value=JSON.stringify(draft.value)}
async function save(){if(!draft.value||saving.value)return;saving.value=true;error.value='';try{const r=(await (draft.value.id?api.put<{rig:Rig}>(`/api/rigs/${draft.value.id}`,draft.value):api.post<{rig:Rig}>('/api/rigs',draft.value))).rig;draft.value=null;await load();await router.push(`/garage/rigs/${r.id}`)}catch(e){error.value=String(e)}finally{saving.value=false}}
async function remove(rig:Rig){if(!await confirm.ask({title:`Remove ${rig.name}?`,message:'Remove the equipment inventory record. Drivers and history remain available. Detach attached cameras first.',confirmLabel:'Remove rig'}))return;try{await api.delete(`/api/rigs/${rig.id}`);await router.push('/garage/rigs');await load()}catch(e){error.value=String(e)}}
function editCamera(source?:CameraSource){check.value='';error.value='';camera.value=source?JSON.parse(JSON.stringify(source)):{id:'',name:'',enabled:true,player_url:'',status_url:'',capture_url:'',recording_configured:false,driver_guid:'',instance_id:null,rig_id:selected.value?.id??null};cameraBaseline.value=JSON.stringify(camera.value)}
async function saveCamera(){if(!camera.value||saving.value)return;saving.value=true;error.value='';try{await (camera.value.id?api.put(`/api/sources/${encodeURIComponent(camera.value.id)}`,camera.value):api.post('/api/sources',camera.value));camera.value=null;await streams.loadStreams()}catch(e){error.value=String(e)}finally{saving.value=false}}
async function checkCamera(source:CameraSource){check.value='Checking saved source…';try{const result=await api.post<{statuses:Record<string,{status:string}>}>(`/api/sources/${encodeURIComponent(source.id)}/check`);const h=result.statuses[source.id];check.value=h?.status==='live'?'The saved status endpoint responded. Open Live to verify playback; recorder health is checked separately.':`Saved source status: ${h?.status??'unknown'}. URL validation does not prove playback or recording.`}catch(e){check.value=String(e)}}
watch(()=>route.query.source,()=>{const source=streams.sources.value.find(s=>s.id===route.query.source);if(source&&auth.isAdmin)editCamera(source)});
onMounted(load);
</script>
<template>
<header class="pitlane-heading"><div><span class="pitlane-eyebrow">Garage / Rigs & cameras</span><h1>{{ selected?.name || 'Ready for the next driver.' }}</h1><p>{{ selected?.location || 'Equipment stays with the seat. Results stay with the person.' }}</p></div><div class="pitlane-actions"><RouterLink to="/garage" class="pitlane-button">Garage</RouterLink><button v-if="auth.isAdmin" class="pitlane-button primary" @click="edit(selected)">{{ selected?'Edit rig':'Add rig' }}</button></div></header>
<div v-if="error && !draft && !camera" role="alert" class="pitlane-error">{{ error }} <button @click="load">Retry</button></div>
<div v-if="!loaded && !error">Loading equipment…</div>
<template v-else-if="selected"><RouterLink to="/garage/rigs" class="pitlane-button mb-6">← All rigs</RouterLink><div class="rig-detail"><div class="pitlane-card"><ScreenSetupArt :setup="selected.display" class="rig-illustration" /><h2>{{ artwork(selected.display).name }}</h2><p>{{ selected.notes || 'No equipment notes yet.' }}</p></div><div class="pitlane-card"><h2>At the wheel</h2><p>Current driver: {{ occupants(selected).join(', ') || 'No active game connection' }}</p><p>Usual driver: {{ usualName(selected) }}</p><p class="text-sm">The usual driver is a default. Current attribution comes from the server assignment.</p><div v-if="auth.canOperate" class="pitlane-actions mt-4"><button v-for="seat in currentSeats(selected)" :key="`${seat.instanceId}:${seat.carId}`" class="pitlane-button" @click="handover=seat;nextGuest=null">Next driver · {{ seat.name }}</button><RouterLink to="/guest-drivers" class="pitlane-button">Guest roster</RouterLink></div><h3 class="mt-8 mb-4">Gear</h3><div v-for="gear in selected.gear" :key="gear.id" class="py-3 border-b border-line"><b>{{ gear.name }}</b><span class="text-muted text-sm block">{{ gear.type }} · {{ gear.notes }}</span></div><p v-if="!selected.gear.length">Add a wheel, pedals, cockpit or other equipment in Edit rig.</p><button v-if="auth.isAdmin" class="pitlane-button mt-6" @click="remove(selected)">Remove rig</button></div></div></template>
<template v-else><label class="pitlane-field mb-6"><span>Find a rig or piece of equipment</span><input v-model="search" type="search" placeholder="Name, location or gear…" /></label><div v-if="loaded && !rigs.length" class="pitlane-empty"><h2 class="text-2xl">Give every seat a home.</h2><p>Add the rig’s name, screens, location and gear. Attach cameras when they’re ready.</p><button v-if="auth.isAdmin" class="pitlane-button primary" @click="edit()">Add your first rig</button></div><div class="pitlane-grid"><RouterLink v-for="rig in visible" :key="rig.id" :to="`/garage/rigs/${rig.id}`" class="pitlane-card rig-card"><ScreenSetupArt :setup="rig.display" class="rig-illustration" /><h2>{{ rig.name }}</h2><p>{{ rig.location || 'Location not set' }} · {{ artwork(rig.display).name }}</p><p>{{ occupants(rig).join(', ') || 'No active game connection' }}</p><p>{{ attached(rig.id).length }} attached cameras →</p></RouterLink></div></template>
<section class="pitlane-section"><div class="pitlane-heading"><h2 class="text-2xl">{{ selected?'Attached cameras':'All cameras' }}</h2><button v-if="auth.isAdmin" class="pitlane-button" @click="editCamera()">Add camera</button></div><p v-if="streams.error.value" role="alert" class="pitlane-error">{{ streams.error.value }}</p><div class="pitlane-stack"><article v-for="source in selected?attached(selected.id):streams.sources.value" :key="source.id" class="pitlane-card source-row"><div><h3>{{ source.name }}</h3><p>{{ source.enabled?'Enabled':'Disabled' }} · {{ source.rig_id ? rigs.find(r=>r.id===source.rig_id)?.name || 'Attached rig' : 'Standalone' }}</p><small class="text-muted">{{ source.recording_configured?'Recording source configured; verify recorder health.':'Playback only; no recording source configured.' }}</small></div><div class="pitlane-actions"><RouterLink :to="`/garage/cameras/${encodeURIComponent(source.id)}`" class="pitlane-button">Watch & moments</RouterLink><button v-if="auth.isAdmin" class="pitlane-button" @click="editCamera(source)">Stream setup</button></div></article></div><p v-if="loaded&&!streams.sources.value.length" class="text-muted">No cameras configured. Add a player URL from your simulator or spectator feed.</p></section>
<Sheet :open="!!draft" :title="draft?.id?'Edit rig':'Add rig'" @close="closeEditor(()=>{draft=null})"><form v-if="draft" class="pitlane-stack" @submit.prevent="save"><div v-if="error" role="alert" class="pitlane-error">{{ error }}</div><label class="pitlane-field">Rig name<input v-model="draft.name" required maxlength="160" /></label><label class="pitlane-field">Location<input v-model="draft.location" maxlength="500" placeholder="Upstairs, left seat…" /></label><fieldset><legend class="mb-3">Display arrangement</legend><div class="display-options"><label v-for="display in screenSetups" :key="display.id" :class="{chosen:draft.display===display.id}"><input v-model="draft.display" type="radio" name="display" :value="display.id" /><ScreenSetupArt :setup="display.id" /><span>{{ display.name }}</span></label></div></fieldset><label class="pitlane-field">Notes<textarea v-model="draft.notes" maxlength="10000" /></label><details><summary class="min-h-11">Usual driver (optional)</summary><p class="text-sm text-muted mb-3">A default, separate from the person currently driving.</p><label class="pitlane-field">Account driver<select v-model="draft.usual_driver_guid" @change="draft.usual_guest_id=null"><option value="">Anyone / choose a guest</option><option v-for="driver in accounts" :key="driver.guid" :value="driver.guid">{{ driver.name }}</option></select></label><label class="pitlane-field">Guest driver<select v-model="draft.usual_guest_id" @change="draft.usual_driver_guid='' "><option :value="null">No usual guest</option><option v-for="guest in guests" :key="guest.id" :value="guest.id">{{ guest.name }}</option></select></label></details><fieldset class="pitlane-stack"><legend class="mb-4">Gear</legend><div v-for="(gear,index) in draft.gear" :key="gear.id" class="pitlane-card pitlane-stack"><label class="pitlane-field">Type<select v-model="gear.type"><option v-for="type in ['Wheelbase','Wheel','Pedals','Shifter','Handbrake','Cockpit / seat','Screens','VR headset','PC','Motion','Haptics','Other']" :key="type">{{ type }}</option></select></label><label class="pitlane-field">Name / model<input v-model="gear.name" required maxlength="300" /></label><label class="pitlane-field">Gear notes<input v-model="gear.notes" maxlength="2000" /></label><button type="button" class="pitlane-button" @click="draft.gear.splice(index,1)">Remove gear item</button></div><button type="button" class="pitlane-button" @click="draft.gear.push({id:newGearId(),type:'Wheelbase',name:'',notes:''})">Add gear</button></fieldset><button class="pitlane-button primary" :disabled="saving">{{ saving?'Saving…':'Save rig' }}</button></form></Sheet>
<Sheet :open="!!camera" title="Stream setup" @close="closeEditor(()=>{camera=null})"><form v-if="camera" class="pitlane-stack" @submit.prevent="saveCamera"><p class="text-muted">Use a WHEP endpoint or an embeddable player link. A saved URL is not proof of a connected source.</p><div v-if="error" role="alert" class="pitlane-error">{{ error }}</div><label class="pitlane-field">Camera name<input v-model="camera.name" required maxlength="160" /></label><label class="pitlane-field">Player URL<input v-model="camera.player_url" type="url" required /></label><label class="pitlane-field">Attached rig<select v-model="camera.rig_id"><option :value="null">Standalone camera</option><option v-for="rig in rigs" :key="rig.id" :value="rig.id">{{ rig.name }}</option></select></label><label class="flex gap-3"><input v-model="camera.enabled" type="checkbox" />Enable playback</label><details><summary class="min-h-11">Association and source status</summary><label class="pitlane-field">Account driver GUID<input v-model="camera.driver_guid" :disabled="camera.id.startsWith('driver:')" /></label><label class="pitlane-field">Server association<select v-model="camera.instance_id" :disabled="camera.id.startsWith('spectator:')"><option :value="null">Independent of a server</option><option v-for="i in server.instanceList" :key="i.id" :value="i.id">{{ i.name }}</option></select></label><label class="pitlane-field mt-4">Status URL (optional)<input v-model="camera.status_url" type="url" /></label><button v-if="camera.id" class="pitlane-button mt-3" type="button" @click="checkCamera(camera)">Check saved connection</button><p v-if="check" role="status" class="text-sm mt-3">{{ check }}</p></details><details v-if="!camera.id.startsWith('spectator:')"><summary class="min-h-11">Recording (optional)</summary><label class="pitlane-field">Server-reachable recording URL<input v-model="camera.capture_url" placeholder="HLS, RTSP, RTMP or SRT source" /></label><p class="text-sm text-muted mt-3">Player embeds cannot be recorded directly. Inspect actual recorder readiness before capturing.</p><RouterLink to="/settings/streams" class="pitlane-button mt-3">Recorder diagnostics</RouterLink></details><button class="pitlane-button primary" :disabled="saving">{{ saving?'Saving…':'Save camera' }}</button></form></Sheet>
<Sheet :open="!!handover" title="Next driver" @close="handover=null"><form class="pitlane-stack" @submit.prevent="changeDriver"><p>Stop the car and finish the active drift run. This closes the previous driver’s result segment and any manual recording, then changes future attribution.</p><p>Current driver: {{ handover?.name }}</p><div v-if="error" class="pitlane-error" role="alert">{{ error }}</div><label class="pitlane-field">Next driver<select v-model="nextGuest"><option :value="null">Use the connected account’s name</option><option v-for="guest in guests" :key="guest.id" :value="guest.id">{{ guest.name }}</option></select></label><button class="pitlane-button primary" :disabled="saving">Hand over this seat</button></form></Sheet>
</template>
<style scoped>.rig-detail{display:grid;grid-template-columns:1fr 1fr;gap:24px}.rig-illustration{width:100%;height:220px;object-fit:contain;margin:0 auto 22px}.rig-detail .rig-illustration{height:330px}.rig-card:hover{border-color:var(--color-accent)}.source-row{display:flex;justify-content:space-between;gap:20px;align-items:center;flex-wrap:wrap}.display-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.display-options label{position:relative;border:1px solid var(--color-line);border-radius:9px;padding:12px;cursor:pointer}.display-options .chosen{border-color:var(--color-accent);background:var(--color-accent-dim)}.display-options img{width:100%;height:90px;object-fit:contain}.display-options span{font-size:12px;display:block;margin-top:8px}.display-options input{accent-color:var(--color-accent)}@media(max-width:767px){.rig-detail{grid-template-columns:1fr}.display-options{grid-template-columns:repeat(2,minmax(0,1fr))}.rig-detail .rig-illustration{height:230px}}</style>
