<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';
import {api} from '@/lib/api';
import {useAuthStore} from '@/stores/auth';
import type {DrivingSession} from '@/lib/drivingSessions';
import TrackImage from '@/components/TrackImage.vue';
const auth=useAuthStore(),sessions=ref<DrivingSession[]>([]),error=ref(''),loaded=ref(false),filter=ref('all');
const shown=computed(()=>sessions.value.filter(s=>filter.value==='all'||filter.value==='upcoming'&&['draft','planned','queued'].includes(s.lifecycle)||filter.value==='live'&&['live','starting'].includes(s.lifecycle)||filter.value==='finished'&&['finished','failed','cancelled'].includes(s.lifecycle)));
async function load(){try{sessions.value=(await api.get<{sessions:DrivingSession[]}>('/api/driving-sessions')).sessions;error.value='';loaded.value=true}catch(e){error.value=String(e)}}onMounted(load);
</script>
<template><header class="pitlane-heading"><div><span class="pitlane-eyebrow">From the first idea to one more lap</span><h1>Your sessions<span class="text-accent">.</span></h1><p>Plan the next drive. Pick up where you left off. Do a good evening again.</p></div><RouterLink v-if="auth.canOperate" to="/sessions/new" class="pitlane-button primary">New session →</RouterLink></header><div class="pitlane-tabs"><button v-for="(label,value) in {all:'All sessions',upcoming:'Coming up',live:'On track',finished:'Finished'}" :key="value" :aria-pressed="filter===value" @click="filter=value">{{ label }}</button></div><div class="pitlane-actions mb-7"><RouterLink to="/sessions/drives" class="pitlane-button">Search driving stints</RouterLink><RouterLink to="/history" class="pitlane-button">Result files</RouterLink><RouterLink to="/events" class="pitlane-button">Reusable setups</RouterLink><RouterLink to="/queue" class="pitlane-button">Queue & repeat</RouterLink></div><p v-if="error" role="alert" class="pitlane-error">{{ error }} <button class="underline" @click="load">Retry</button></p><p v-if="!loaded&&!error">Loading sessions…</p><div v-else-if="loaded&&!shown.length" class="pitlane-empty"><h2 class="text-2xl">A new evening starts here.</h2><p>{{ sessions.length?'No sessions in this view.':'Create a driving session, or find older drives using Search driving stints.' }}</p><RouterLink v-if="auth.canOperate" to="/sessions/new" class="pitlane-button primary">Choose your experience →</RouterLink></div><div class="pitlane-grid"><RouterLink v-for="s in shown" :key="s.id" :to="`/sessions/${s.id}`" class="pitlane-card session-card"><TrackImage :track-key="s.setup.track_key" :config="s.setup.track_config" class="h-44 rounded-lg mb-5" /><span class="pitlane-eyebrow">{{ s.experience }} · {{ s.lifecycle }}</span><h2>{{ s.name }}</h2><p>{{ s.setup.track_key }}{{ s.setup.track_config ? ' / '+s.setup.track_config : '' }}</p><p v-if="s.scheduled_at">{{ new Date(s.scheduled_at).toLocaleString() }} · {{ s.time_zone }}</p><p v-if="s.failure" class="text-danger">{{ s.failure }}</p></RouterLink></div></template>
<style scoped>.session-card:hover{border-color:var(--color-accent)}</style>
