<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {api} from '@/lib/api';
import {useServerStore} from '@/stores/server';
import {useAuthStore} from '@/stores/auth';
import {useContentStore} from '@/stores/content';
import {useUnsavedGuard} from '@/lib/useUnsavedGuard';
import type {DrivingSession} from '@/lib/drivingSessions';
import type {PreviewResult} from '@/lib/useRaceSetupPreview';
import TrackPicker from '@/components/TrackPicker.vue';
import TrackImage from '@/components/TrackImage.vue';
import DifficultyFields from '@/components/presets/DifficultyFields.vue';
import SessionFields from '@/components/presets/SessionFields.vue';
import ClassFields from '@/components/presets/ClassFields.vue';
import TimeFields from '@/components/presets/TimeFields.vue';
const route=useRoute(),router=useRouter(),server=useServerStore(),auth=useAuthStore(),content=useContentStore();
const session=ref<DrivingSession|null>(null),error=ref(''),busy=ref(false),saved=ref(''),recoveryMessage=ref(''),trackPicker=ref(false),review=ref<(PreviewResult & {instance_id:number})|null>(null);
const instance=ref<number|null>(Number(route.query.instance)||null),mode=ref('now'),localTime=ref(''),zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
const cacheKey=()=>`pitlane.draft.${auth.user?.name}.${route.params.sessionId || 'new'}`;
const operationKey=ref('');
const gridCount=computed(()=>session.value?.setup.grid.entries?.reduce((n,e)=>n+(e.count??1),0)??0);
const dirty=computed(()=>!!session.value&&JSON.stringify(session.value)!==saved.value);
useUnsavedGuard(()=>dirty.value,true,()=>{try{localStorage.removeItem(cacheKey())}catch{}});
watch(session,()=>{review.value=null;try{if(session.value&&dirty.value)localStorage.setItem(cacheKey(),JSON.stringify(session.value));else localStorage.removeItem(cacheKey())}catch{/* Server save remains available. */}},{deep:true});
async function choose(experience:string){busy.value=true;error.value='';try{session.value=await api.get<DrivingSession>(`/api/driving-sessions/defaults?experience=${experience}`)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function load(){busy.value=true;try{await content.load();if(route.params.sessionId){session.value=await api.get<DrivingSession>(`/api/driving-sessions/${route.params.sessionId}`);saved.value=JSON.stringify(session.value);try{const cached=JSON.parse(localStorage.getItem(cacheKey())||'null') as DrivingSession|null;if(cached?.id===session.value.id&&cached.revision===session.value.revision&&JSON.stringify(cached)!==saved.value){session.value=cached;recoveryMessage.value='Recovered your unsaved changes on this device.'}}catch{}}else if(route.query.template){session.value=await api.get<DrivingSession>(`/api/driving-sessions/template/${route.query.template}`);instance.value=Number(route.query.instance)||null}else if(route.query.again){const old=await api.get<DrivingSession>(`/api/driving-sessions/${route.query.again}`);session.value={...old,id:0,revision:0,lifecycle:'draft',name:old.name,instance_id:null,event_id:null,started_at:null,ended_at:null,scheduled_at:null,failure:''}}else{try{const draft=localStorage.getItem(cacheKey());if(draft)session.value=JSON.parse(draft)}catch{/* Corrupt local recovery must not prevent a new session. */}}}catch(e){error.value=String(e)}finally{busy.value=false}}
async function save(){if(!session.value)return;busy.value=true;error.value='';try{const s=session.value;session.value=await(s.id?api.put<DrivingSession>(`/api/driving-sessions/${s.id}`,s):api.post<DrivingSession>('/api/driving-sessions',s));saved.value=JSON.stringify(session.value);try{localStorage.removeItem(cacheKey())}catch{};if(!route.params.sessionId)await router.replace(`/sessions/${session.value.id}/edit`);return true}catch(e){error.value=String(e);return false}finally{busy.value=false}}
async function preview(){if(!session.value)return;if(dirty.value||!session.value.id){if(!await save())return}busy.value=true;error.value='';try{review.value=await api.post<PreviewResult & {instance_id:number}>(`/api/driving-sessions/preview?mode=${mode.value}`,{...session.value,instance_id:instance.value})}catch(e){error.value=String(e)}finally{busy.value=false}}
async function start(){if(!session.value||busy.value||!review.value)return;if(dirty.value){error.value='Review your latest changes before starting.';return}busy.value=true;error.value='';try{const s=session.value;const request={expected_revision:s.revision,instance_id:review.value.instance_id,mode:mode.value,scheduled_at:mode.value==='later'?new Date(localTime.value).getTime():null,time_zone:zone};const operationStorage=`pitlane.launch.${auth.user?.name}.${s.id}`;const fingerprint=JSON.stringify(request);try{const previous=JSON.parse(localStorage.getItem(operationStorage)||'null');operationKey.value=previous?.fingerprint===fingerprint?previous.key:crypto.randomUUID();localStorage.setItem(operationStorage,JSON.stringify({fingerprint,key:operationKey.value}))}catch{operationKey.value ||= crypto.randomUUID()};await api.post(`/api/driving-sessions/${s.id}/start`,{...request,idempotency_key:operationKey.value});saved.value=JSON.stringify(s);await server.bootstrapLiveState();await router.push(`/sessions/${s.id}`)}catch(e){error.value=String(e)}finally{busy.value=false}}
watch([instance,mode,localTime],()=>{review.value=null;operationKey.value=''});
onMounted(load);
</script>
<template>
<header class="pitlane-heading"><div><span class="pitlane-eyebrow">Sessions / {{ session?.id?'Edit session':'New session' }}</span><h1>{{ session?'Make it your drive.':'What do you feel like driving?' }}</h1><p>{{ session?'A complete setup, ready to review. Change only what you need.':'Choose an experience. We’ll start with what’s installed in your club.' }}</p></div><RouterLink to="/sessions" class="pitlane-button">All sessions</RouterLink></header>
<p v-if="recoveryMessage" role="status" class="mb-5">{{ recoveryMessage }}</p><div v-if="error" class="pitlane-error" role="alert">{{ error }}<div class="pitlane-actions mt-3"><RouterLink to="/garage/content" class="pitlane-button" v-if="auth.isAdmin">Cars & tracks</RouterLink><RouterLink to="/setup" class="pitlane-button" v-if="auth.isAdmin">Installation & readiness</RouterLink></div></div>
<p v-if="busy&&!session" role="status">Preparing installed-content defaults…</p>
<div v-if="!session" class="pitlane-grid experience-grid"><button v-for="experience in [{id:'drift',title:'Drift',text:'Open drifting. Find your flow with the club.',symbol:'↝'},{id:'race',title:'Race',text:'Practice, qualifying, and a race. A complete evening.',symbol:'⚑'},{id:'practice',title:'Practice',text:'A few laps, a new car, or just time on track.',symbol:'↻'}]" :key="experience.id" class="pitlane-card experience-card" :disabled="busy" @click="choose(experience.id)"><span class="experience-symbol" aria-hidden="true">{{ experience.symbol }}</span><h2>{{ experience.title }}</h2><p>{{ experience.text }}</p><span class="block mt-6">Prepare {{ experience.title.toLowerCase() }} →</span></button></div>
<div v-else class="session-builder"><div class="pitlane-stack"><label class="pitlane-field">Session name<input v-model="session.name" maxlength="160" /></label><section class="session-setting"><div><span>Track & layout</span><h2>{{ content.trackByKey(session.setup.track_key,session.setup.track_config)?.name || session.setup.track_key }}</h2><p>{{ session.setup.track_config || 'Default layout' }}</p></div><button class="pitlane-button" @click="trackPicker=true">Change track</button></section><details class="session-setting-details"><summary><span>Cars & grid</span><b>{{ gridCount }} grid slots</b><span>Change →</span></summary><ClassFields v-model="session.setup.grid" /></details><details class="session-setting-details"><summary><span>Driving phases</span><b>{{ session.experience }}</b><span>Change →</span></summary><SessionFields v-model="session.setup.phases" /><label class="pitlane-field mt-4">Race laps (0 uses timed race)<input v-model.number="session.setup.race_laps" type="number" min="0" max="10000" /></label></details><details class="session-setting-details"><summary><span>Time & weather</span><b>{{ session.setup.conditions.time }}</b><span>Change →</span></summary><TimeFields v-model="session.setup.conditions" /></details><details class="session-setting-details"><summary><span>Assists, realism & grip</span><span>Advanced →</span></summary><DifficultyFields v-model="session.setup.difficulty" /></details><details v-if="session.experience==='drift'" class="session-setting-details"><summary><span>Drift scoring</span><span>Advanced →</span></summary><p class="text-muted text-sm mb-4">These values belong to this session. Shared scoring modes remain unchanged.</p><div class="pitlane-grid"><label v-for="(_,field) in session.setup.scoring" v-show="field!=='id'&&field!=='name'" :key="field" class="pitlane-field"><span>{{ field.replaceAll('_',' ') }}</span><input v-if="field!=='id'&&field!=='name'" v-model.number="session.setup.scoring[field]" type="number" step="any" /></label></div></details><details class="session-setting-details"><summary>Custom INI overrides · Advanced</summary><p class="text-sm text-muted mb-4">Session-scoped driving controls. Supported sections: PRACTICE and QUALIFY (TIME, IS_OPEN), RACE (TIME, WAIT_TIME, IS_OPEN), DYNAMIC_TRACK (SESSION_START, SESSION_TRANSFER, LAP_GAIN), SERVER (ABS_ALLOWED, TC_ALLOWED, AUTOCLUTCH_ALLOWED, TYRE_BLANKETS_ALLOWED, FUEL_RATE, TYRE_WEAR_RATE, DAMAGE_MULTIPLIER). Preview validates the effective values.</p><label class="pitlane-field">Overrides<textarea v-model="session.setup.custom_ini" rows="8" maxlength="16000" placeholder="[PRACTICE]&#10;TIME=30" class="font-mono"/></label></details><button class="pitlane-button" :disabled="busy" @click="save">{{ busy?'Saving…':dirty?'Save draft':'Draft saved' }}</button></div>
<aside class="pitlane-card builder-review"><TrackImage :track-key="session.setup.track_key" :config="session.setup.track_config" class="h-44 rounded-lg mb-5" /><span class="pitlane-eyebrow">{{ session.experience }} · Your session</span><h2>{{ session.name }}</h2><p>{{ gridCount }} cars · {{ session.setup.track_config || 'Default layout' }}</p><label class="pitlane-field mt-5">Server<select v-model="instance"><option :value="null">Choose a free compatible server</option><option v-for="i in server.instanceList" :key="i.id" :value="i.id">{{ i.name }}{{ i.running?' · running':'' }}</option></select></label><label class="pitlane-field mt-5">When<select v-model="mode"><option value="now">Start now</option><option value="after">After current · add to the queue</option><option value="later">Later · schedule a start</option></select></label><label v-if="mode==='later'" class="pitlane-field mt-4">Date & time<input v-model="localTime" type="datetime-local" /><small>{{ zone }} · Starts when the server is free; overruns can delay it.</small></label><button class="pitlane-button w-full mt-5" :disabled="busy" @click="preview">Review exact configuration</button><div v-if="review" class="mt-4"><p>Reviewed for {{ server.instances[review.instance_id]?.name || `server ${review.instance_id}` }}</p><p>{{ review.grid_count }} rendered slots · {{ review.pitboxes }} pitboxes</p><p v-for="warning in [...review.warnings,...review.render_errors]" :key="warning" class="text-warn">{{ warning }}</p><details class="mt-3"><summary>Inspect generated files</summary><h3 class="mt-3">server_cfg.ini</h3><pre class="text-xs overflow-auto max-h-80">{{ review.server_cfg }}</pre><h3 class="mt-3">entry_list.ini</h3><pre class="text-xs overflow-auto max-h-80">{{ review.entry_list }}</pre></details></div><button class="pitlane-button primary w-full mt-5" :disabled="busy||!review||!!review.render_errors.length" @click="start">{{ busy?'Working…':mode==='now'?'Start this session':mode==='after'?'Add this session to the queue':'Schedule this session' }}</button><p class="text-sm">The server rechecks content, capacity and availability. Running sessions stay in place.</p></aside></div>
<TrackPicker :open="trackPicker" @close="trackPicker=false" @select="track=>{if(session){session.setup.track_key=track.key;session.setup.track_config=track.config}trackPicker=false}" />
</template>
<style scoped>.experience-card{text-align:left;padding:30px;min-height:280px}.experience-card:hover{border-color:var(--color-accent)}.experience-symbol{display:block;font-size:80px;line-height:1.4;color:var(--color-accent)}.session-builder{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(310px,1fr);gap:48px}.builder-review{position:sticky;top:24px;align-self:start}.session-setting{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--color-line);padding:22px 0}.session-setting span,.session-setting p{color:var(--color-muted);font-size:13px}.session-setting h2{font-size:20px;margin:7px 0}.session-setting-details{padding:18px 0;border-bottom:1px solid var(--color-line)}.session-setting-details>summary{min-height:44px;display:flex;justify-content:space-between;gap:15px;align-items:center;font-size:14px}.session-setting-details[open]>summary{margin-bottom:20px}.session-setting-details summary>b{font-weight:500;text-transform:capitalize}@media(max-width:900px){.session-builder{grid-template-columns:1fr;gap:28px}.builder-review{position:static}}
</style>
