FROM golang:alpine

RUN apk --no-cache add gcc g++ make git npm p7zip
ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /go/src/app

ENV GOMODCACHE=/go/pkg/mod
ENV GOCACHE=/root/.cache/go-build

EXPOSE 3030
EXPOSE 9600/tcp
EXPOSE 9600/udp
EXPOSE 8081

CMD ["sh", "-lc", "(test -f src/embed/webapp/dist/index.html || (cd webapp && npm install && npm run build)) && cd src && /usr/local/go/bin/go run . -debug -p /appdata"]
