FROM golang:alpine

RUN apk --no-cache add gcc g++ make git npm

WORKDIR /go/src/app

EXPOSE 3030
EXPOSE 9600/tcp
EXPOSE 9600/udp
EXPOSE 8081

CMD ["sh", "-lc", "test -d node_modules/tailwindcss || npm install --include=optional && npx @tailwindcss/cli -i ./css/input.css -o ./css/main.css && test -f src/assets.go || (/usr/local/go/bin/go install github.com/jessevdk/go-assets-builder@latest && /go/bin/go-assets-builder schema.sql favicon.ico ini htm img css -o src/assets.go) && /usr/local/go/bin/go get main/src && cd src && /usr/local/go/bin/go run . -debug -p /appdata"]
