services:
  servermanager:
    container_name: assetto-server-manager
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    volumes:
      - ${APP_PATH:-./}/assetocorsa:/corsa/:ro
      - ${APP_PATH:-./}/data:/appdata/:rw
    ports:
      - 3030:3030
      - ${AC_TCP_PORT:-9600}:9600/tcp
      - ${AC_UDP_PORT:-9600}:9600/udp
      - ${AC_HTTP_PORT:-8081}:8081/tcp
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.assetto-server-manager-bridge.entrypoints=https"
      - "traefik.http.routers.assetto-server-manager-bridge.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.assetto-server-manager-bridge.tls=true"
      - "traefik.http.services.assetto-server-manager-bridge.loadbalancer.server.port=3030"

networks:
  proxy:
    external: true
