// Code generated by tygo. DO NOT EDIT.
// Generated by tygo from src/dbmodels.go — do not edit.
// Regenerate with: make types

//////////
// source: dbmodels.go

export interface Users {
  name?: string;
  password?: string;
  measurement_unit?: number /* int */;
  temp_unit?: number /* int */;
  role?: string;
}
export interface UserConfig {
  name?: string;
  password?: string;
  admin_password?: string;
  register_to_lobby?: number /* int */;
  locked_entry_list?: number /* int */;
  result_screen_time?: number /* int */;
  udp_port?: number /* int */;
  tcp_port?: number /* int */;
  http_port?: number /* int */;
  client_send_interval?: number /* int */;
  num_threads?: number /* int */;
  max_clients?: number /* int */;
  welcome_message?: string;
  append_eventname?: number /* int */;
  append_modlinks?: number /* int */;
  mod_download_url?: string;
  server_engine?: string;
  as_relax_checksums?: number /* int */;
  auto_start_server?: number /* int */;
  install_path?: string;
  csp_required?: number /* int */;
  csp_version?: number /* int */;
  csp_phycars?: number /* int */;
  csp_phytracks?: number /* int */;
  csp_hidepit?: number /* int */;
  cfg_filled?: number /* int */;
  mod_filled?: number /* int */;
  capture_enabled?: number /* int */;
  capture_screenshots?: number /* int */;
  capture_clips?: number /* int */;
  capture_trigger_score?: number /* int */;
  capture_clip_seconds?: number /* int */;
  capture_cooldown_seconds?: number /* int */;
  capture_max_per_session?: number /* int */;
}
export interface ServerEvent {
  Id?: number /* int */;
  UserEvent: UserEvent;
  ServerCfg?: string;
  EntryList?: string;
  StartedAt?: number /* int64 */;
  Finished?: number /* int */;
  instance_id?: number /* int */;
}
export interface ServerInstance {
  id?: number /* int */;
  name?: string;
  udp_port?: number /* int */;
  tcp_port?: number /* int */;
  http_port?: number /* int */;
  plugin_port?: number /* int */;
  plugin_listen_port?: number /* int */;
  enabled?: number /* int */;
  stream_enabled?: number /* int */;
  stream_embed_url?: string;
  stream_status_url?: string;
  spectator_enabled?: number /* int */;
  spectator_driver_name?: string;
  spectator_guid?: string;
  spectator_car_key?: string;
  spectator_skin_key?: string;
  /**
   * RunMode is "manual_queue" (default) or "repeat_event". In repeat mode the
   * instance re-applies RepeatEventId every time a session ends instead of
   * advancing the manual queue.
   */
  run_mode?: string;
  repeat_event_id?: number /* int */;
  /**
   * ScheduledStart is a unix timestamp; the scheduler starts the instance at
   * or after this time, then clears it. nil/0 means no schedule.
   */
  scheduled_start?: number /* int64 */;
  /**
   * StartOnBoot auto-starts this instance from its queue when SM launches.
   */
  start_on_boot?: number /* int */;
  /**
   * DriftScoreEnabled serves the drift-score CSP Lua HUD to clients. Only has
   * an effect on the AssettoServer engine (vanilla acServer has no CSP-script
   * delivery channel).
   */
  drift_score_enabled?: number /* int */;
  drift_scoring_mode_id?: number /* int */;
  /**
   * AllowWrongWay writes [EXTRA_RULES] ALLOW_WRONG_WAY=1 into csp_extra_options.ini,
   * letting drivers go the wrong way without the CSP "back to pits" teleport.
   * Only has an effect on the AssettoServer engine (it delivers the extra
   * options via the CSP handshake; vanilla acServer ignores the file).
   */
  allow_wrong_way?: number /* int */;
}
export interface DriverStream {
  id?: number /* int */;
  driver_guid?: string;
  display_name?: string;
  enabled?: number /* int */;
  stream_embed_url?: string;
  stream_status_url?: string;
  stream_capture_url?: string;
}
export interface UserEvent {
  Id?: number /* int */;
  name?: string;
  EventCategoryId?: number /* int */;
  CategoryName?: string;
  race_laps?: number /* int */;
  strategy?: number /* int */;
  TrackName?: string;
  TrackLength?: number /* int */;
  Pitboxes?: number /* int */;
  DifficultyName?: string;
  AbsAllowed?: number /* int */;
  TcAllowed?: number /* int */;
  StabilityAllowed?: number /* int */;
  AutoclutchAllowed?: number /* int */;
  SessionName?: string;
  BookingEnabled?: number /* int */;
  BookingTime?: number /* int */;
  PracticeEnabled?: number /* int */;
  PracticeTime?: number /* int */;
  QualifyEnabled?: number /* int */;
  QualifyTime?: number /* int */;
  RaceEnabled?: number /* int */;
  RaceTime?: number /* int */;
  ClassName?: string;
  Entries?: number /* int */;
  TimeName?: string;
  Time?: string;
  Graphics?: string;
  TruncWeather?: number /* int */;
  CspWeather?: number /* int */;
  CacheTrackKey?: string;
  CacheTrackConfig?: string;
  track?: string;
  difficulty?: number /* int */;
  session?: number /* int */;
  class?: number /* int */;
  time?: number /* int */;
  drift_scoring_mode_id?: number /* int */;
}
export interface UserEventList {
  id?: number /* int */;
  event_category_id?: number /* int */;
  name?: string;
  track_name?: string;
}
export interface UserEventCategory {
  id?: number /* int */;
  name?: string;
  events: UserEvent[];
}
export interface DriftScoringMode {
  id?: number /* int */;
  name?: string;
  collision_reset_score?: number /* int */;
  car_collision_reset_score?: number /* int */;
  reset_score_enabled?: number /* int */;
  reset_score_seconds?: number;
  reset_multiplier_enabled?: number /* int */;
  reset_multiplier_seconds?: number;
  min_speed_kmh?: number;
  min_angle_deg?: number;
  angle_weight?: number;
  speed_weight?: number;
  proximity_weight?: number;
  proximity_range_m?: number;
  multiplier_gain?: number;
  multiplier_cap?: number /* int */;
}
export interface UserDifficulty {
  id?: number /* int */;
  name?: string;
  abs_allowed?: number /* int */;
  tc_allowed?: number /* int */;
  stability_allowed?: number /* int */;
  autoclutch_allowed?: number /* int */;
  tyre_blankets_allowed?: number /* int */;
  force_virtual_mirror?: number /* int */;
  fuel_rate?: number /* int */;
  damage_multiplier?: number /* int */;
  tyre_wear_rate?: number /* int */;
  allowed_tyres_out?: number /* int */;
  max_ballast_kg?: number /* int */;
  start_rule?: number /* int */;
  race_gas_penality_disabled?: number /* int */;
  dynamic_track?: number /* int */;
  dynamic_track_preset?: number /* int */;
  session_start?: number /* int */;
  randomness?: number /* int */;
  session_transfer?: number /* int */;
  lap_gain?: number /* int */;
  kick_quorum?: number /* int */;
  vote_duration?: number /* int */;
  voting_quorum?: number /* int */;
  blacklist_mode?: number /* int */;
  max_contacts_per_km?: number /* int */;
}
export interface UserSession {
  id?: number /* int */;
  name?: string;
  booking_enabled?: number /* int */;
  booking_time?: number /* int */;
  practice_enabled?: number /* int */;
  practice_time?: number /* int */;
  practice_is_open?: number /* int */;
  qualify_enabled?: number /* int */;
  qualify_time?: number /* int */;
  qualify_is_open?: number /* int */;
  qualify_max_wait_perc?: number /* int */;
  race_enabled?: number /* int */;
  race_time?: number /* int */;
  race_extra_lap?: number /* int */;
  race_over_time?: number /* int */;
  race_wait_time?: number /* int */;
  race_is_open?: number /* int */;
  reversed_grid_positions?: number /* int */;
  race_pit_window_start?: number /* int */;
  race_pit_window_end?: number /* int */;
}
export interface UserTime {
  id?: number /* int */;
  name?: string;
  time?: string;
  time_of_day_multi?: number /* int */;
  csp_enabled?: number /* int */;
  weathers: UserTimeWeather[];
}
export interface UserTimeWeather {
  Id?: number /* int */;
  name?: string;
  UserTimeId?: number /* int */;
  graphics?: string;
  base_temperature_ambient?: number /* int */;
  base_temperature_road?: number /* int */;
  variation_ambient?: number /* int */;
  variation_road?: number /* int */;
  wind_base_speed_min?: number /* int */;
  wind_base_speed_max?: number /* int */;
  wind_base_direction?: number /* int */;
  wind_variation_direction?: number /* int */;
  csp_time?: string;
  csp_time_of_day_multi?: number /* int */;
  csp_date?: string;
}
export interface UserClass {
  id?: number /* int */;
  name?: string;
  entries: UserClassEntry[];
}
export interface UserClassEntry {
  Id?: number /* int */;
  user_class_id?: number /* int */;
  cache_car_key?: string;
  skin_key?: string;
  ballast?: number /* int */;
  count?: number /* int */;
}
export interface DropDownList {
  id?: number /* int */;
  name?: string;
}
export interface CacheCar {
  Id?: number /* int */;
  key?: string;
  name?: string;
  brand?: string;
  description?: string;
  tags?: string[];
  class?: string;
  version?: string;
  content_path?: string;
  modified_at?: number /* int64 */;
  specs: {
    bhp: string;
    torque: string;
    weight: string;
    topspeed: string;
    acceleration: string;
    pwratio: string;
    range: number /* int */;
  };
  torqueCurve: any[][];
  powerCurve: any[][];
  skins: {
    key: string;
    name: string;
  }[];
}
export interface CacheTrack {
  Id?: number /* int */;
  key?: string;
  config?: string;
  name?: string;
  desc?: string;
  tags?: string[];
  country?: string;
  city?: string;
  length?: number /* int */;
  width?: string;
  pitboxes?: number /* int */;
  run?: string;
  version?: string;
  content_path?: string;
  modified_at?: number /* int64 */;
}
export interface CacheWeather {
  Id?: number /* int */;
  key?: string;
  name?: string;
}
